# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: dir
    - run: npm install
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.1
        cache: 'npm'
        cache-dependency-path: '**/**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Add remote origin
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        branch: "main"
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: "thabomaibi1999@gmail.com"
    # - name: Deploy on heroku
    #   run:  git push heroku main
    #   run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    # - name: Clone repo
    #   run: heroku git:clone -a ${{ secrets.HEROKU_APP_NAME }}
    # - name: Deploy to heroku
    #   run: git push heroku main 
